2.22. Разметка внутренних страниц
htmlacademy-adaptive/1946503-mishka-25 pull request #3
Opened 2022-04-03 17:28 UTC by GanievTimur

2022-04-03 20:45 UTC, DoberBober commented on source/form.html
> +        <h1 class="titlecatalog-top__title">Вязание на заказ</h1>
Вынеси в отдельный блок.

2022-04-03 20:45 UTC, DoberBober commented on source/catalog.html
> +        <h1 class="titlecatalog-top__title">Каталог товаров</h1>
Вынеси в отдельный блок.

2022-04-03 20:48 UTC, DoberBober commented on source/catalog.html
> +    <section class="product-card">
По-хорошему тут у тебя блок скписок товаров, а каждая карточка вложенная в список - это то же отдельные блоки.
Типа, 
```
<section class="products-list>
<!-- Тут контейнер, если надо -->
    <section class="products-list__card product-item>
        <!-- Содержимое карточки. -->
    </section>
    ...
</section>

2022-04-03 20:49 UTC, DoberBober commented on source/catalog.html
> +            <a href="#" class="product-card__link">
Эту ссылку удали. Оберни картинку и название в ссылки (две штуки будут).

2022-04-03 20:49 UTC, DoberBober commented on source/catalog.html
> +                <svg width="21" height="18" viewBox="0 0 21 18" fill="none" xmlns="http://www.w3.org/2000/svg">
Иконку оберни в ссылку, чтобы можно было кликнуть и добавить в корзину.

2022-04-03 20:50 UTC, DoberBober commented on source/catalog.html
> +          <svg width="33" height="22" viewBox="0 0 33 22" fill="none" xmlns="http://www.w3.org/2000/svg">
В кнопку оберни.

2022-04-03 20:50 UTC, DoberBober commented on source/catalog.html
> +
Добавь картинку и кнопку с иконкой воспроизведения.

2022-04-03 20:51 UTC, DoberBober commented on source/catalog.html
> +<html lang="en">
ru.

2022-04-03 20:51 UTC, DoberBober commented on source/catalog.html
> +              <a href="#" class="main-nav__link">Каталог товаров</a>
Ссылки проставь, чтобы можно было по страницам переходить.

2022-04-03 20:51 UTC, DoberBober commented on source/form.html
> +<html lang="en">
ru.

2022-04-03 20:52 UTC, DoberBober commented on source/form.html
> +              <span class="form-section-type__description">Аксессуар для интерьера</span>
Текст перенеси внутрь лейбла. От самого спана избавься. Аналогично с чекбоксами тоже.

2022-04-03 20:53 UTC, DoberBober commented on source/form.html
> +                <span class="username-section-form__description">Имя:</span>
Сделай лейблом.

2022-04-03 20:53 UTC, DoberBober commented on source/form.html
> +                <input type="text" name="name" class="username-elements-button" id="name-form" placeholder="Введите ваше имя*">
Полям со звёздочкой сражу пропиши required.

2022-04-03 20:54 UTC, DoberBober commented on source/form.html
> +            <legend class="legend-title contacts-section-form__title-phone">тел</legend>
Тоже лейблы.

2022-04-03 20:54 UTC, DoberBober commented on source/form.html
> +            <p><input type="submit" value="отправить заказ" class="button wishes-section-button"></p>
От параграфа избавься. Инпут замени на button[type="submit"].

2022-04-03 20:54 UTC, DoberBober requested changes
-

2022-04-04 18:53 UTC, GanievTimur commented on source/catalog.html
> +    <section class="product-card">
А в таком формате не подойдет?
<ul class="product-card__list">
          <li class="product-card__item">
            <a href="#" class="product-card__link">
              <img src="/source/img/photo-1-product-card.jpg" alt="Зайчик-попрыгайчик">
              <p class="product-card__link-subtitle">Зайчик-попрыгайчик</p>
              <span class="product-card__link-parameters">Рост 30 см, вес 200 г</span>
              <div class="product-card__link-price">
                <span class="product-card__price">1 200 руб.</span>
                <svg width="21" height="18" viewBox="0 0 21 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path opacity="0.2" d="M20.1884 6.85716H16.6377L13.1884 0.380944C12.9855 -8.61287e-06 12.5797 -0.0952351 12.1739 0.0952412C11.7681 0.285717 11.6667 0.66667 11.8696 1.04762L15.0145 6.85716H5.7826L8.92753 1.04762C9.13043 0.66667 8.92754 0.285717 8.6232 0.0952412C8.2174 -0.0952351 7.8116 0.0952295 7.6087 0.380944L4.1594 6.85716H0.811583C0.405785 6.85716 0 7.14286 0 7.61905C0 8 0.304336 8.38094 0.811583 8.38094H1.01449L1.92753 11.2381C1.72463 11.3333 1.62317 11.5238 1.62317 11.8095C1.62317 12.1905 1.92753 12.4762 2.33332 12.4762L4.05797 18H16.942L18.6667 12.4762C19.0725 12.4762 19.3768 12.1905 19.3768 11.8095C19.3768 11.619 19.2754 11.3333 19.0725 11.2381L19.9855 8.38094H20.1884C20.5942 8.38094 21 8.09524 21 7.61905C21 7.14286 20.5942 6.85716 20.1884 6.85716ZM15.6232 16.4762H5.07247L3.85506 12.381H16.942L15.6232 16.4762ZM17.2464 10.9524H3.34782L2.53623 8.28573H18.058L17.2464 10.9524Z" fill="black"/>
                  </svg>
              </div>
            </a>
          </li>

2022-04-04 18:54 UTC, GanievTimur commented on source/catalog.html
> +    <section class="product-card">
А в таком виде не подходит?
<ul class="product-card__list">
          <li class="product-card__item">

2022-04-04 18:55 UTC, GanievTimur commented on source/catalog.html
> +    <section class="product-card">
То есть так как я сделал (списком) не пойдет?
`<ul class="product-card__list">
          <li class="product-card__item">
            <a href="#" class="product-card__link">`

2022-04-04 19:07 UTC, DoberBober commented on source/catalog.html
> +    <section class="product-card">
Пойдёт, такой вариант тоже допустим.

2022-04-04 19:38 UTC, DoberBober approved these changes
lgtm.

2022-04-04 19:38 UTC, merged