Module3 task1
htmlacademy-adaptive/1946503-mishka-25 pull request #4
Opened 2022-04-10 14:07 UTC by GanievTimur

3.8. Стилизация страниц

2022-04-10 20:08 UTC, DoberBober commented on source/sass/blocks/catalog-top.scss
> +.product-card__list {
Это и последующие стили должны быть в `product-card.scss`.

2022-04-10 20:08 UTC, DoberBober commented on source/sass/blocks/contacts-section.scss
> +.contacts-email__link {
Тоже не там лежат стили.

2022-04-10 20:08 UTC, DoberBober commented on source/sass/blocks/footer.scss
> +.footer-social__list {
Не там.

2022-04-10 20:09 UTC, DoberBober commented on source/sass/blocks/footer.scss
> +.footer-copyright {
Тут можно не выносить в отельный файл, а переименовать в `footer__copyright`.

2022-04-10 20:09 UTC, DoberBober commented on source/sass/blocks/form-section.scss
> +.legend-title {
Не там.

2022-04-10 20:09 UTC, DoberBober commented on source/sass/blocks/form-section.scss
> +.legend-title {
Далее тоже.

2022-04-10 20:10 UTC, DoberBober commented on source/sass/blocks/hero-section.scss
> +.hero-nav__list {
Тут и далее тоже вынести. Или, ещё лучше, сделать элементами.

2022-04-10 20:10 UTC, DoberBober commented on source/sass/blocks/main-header.scss
> +.user-nav__list {
user-nav.

2022-04-10 20:10 UTC, DoberBober commented on source/sass/blocks/production.scss
> +.production-description__title {
Сделай элементом production.

2022-04-10 20:10 UTC, DoberBober commented on source/sass/blocks/reviews-slider-section.scss
> +  &-nickname {
`&--nickname`?

2022-04-10 20:11 UTC, DoberBober commented on source/sass/blocks/weeks-product-section.scss
> +.poduct-table {
Перенести в отдельный файл.

2022-04-10 20:11 UTC, DoberBober commented on source/sass/style.scss
> +@use "./source/sass/blocks/common-styles.scss";
Ты ж и так в папке sass. Просто `./main-header.scss`. Ну и у остальных тоже.

2022-04-10 20:12 UTC, DoberBober commented on source/sass/style.scss
> +@use "./source/sass/blocks/common-styles.scss";
Тут везде `@import` вместо `@use`.

2022-04-10 20:13 UTC, DoberBober requested changes
Осторожнее с файлами, в которых лежат стили. Если сейчас не там прописать, потом будет сложно в нужные места перетаскивать.

Ещё создай fonts.scss, подключи в нём шрифты и заимпорть в основной файл (самым первым).

Ещё, начиная с этого задания, тебе надо перед пушем проверять проект на тесты (`npm run lint`).
Справа должна быть зелёная галочка.
![image](https://user-images.githubusercontent.com/18398812/162638041-4f427cb9-c9dc-49c2-89e2-f15394787824.png)

2022-04-10 20:35 UTC, GanievTimur commented on source/sass/blocks/contacts-section.scss
> +.contacts-email__link {
.contacts-email__link по html находится в contacts-section. Немного не понимаю куда тогда его перенести?

2022-04-10 20:36 UTC, GanievTimur commented on source/sass/blocks/footer.scss
> +.footer-social__list {
Здесь так же .footer-social__list по html находится в footer

2022-04-10 20:38 UTC, DoberBober commented on source/sass/blocks/contacts-section.scss
> +.contacts-email__link {
У тебя стили должны лежать в файле, который называется так же, как и блок.
`contacts-email__link` - это элемент блока `contacts-email`. Значит стили должны лежать в `contacts-email.scss`.

2022-04-10 20:40 UTC, GanievTimur commented on source/sass/blocks/contacts-section.scss
> +.contacts-email__link {
А, ок) теперь понял)

2022-04-10 21:44 UTC, GanievTimur commented on source/sass/style.scss
> +@use "./source/sass/blocks/common-styles.scss";
Поправил, теперь всё поломалось(
из scss в css ничего не переносится(
`Error in plugin "sass"
Message:
    source\sass\style.scss
Error: Can't find stylesheet to import.`

2022-04-10 21:47 UTC, DoberBober commented on source/sass/style.scss
> +@use "./source/sass/blocks/common-styles.scss";
./blocks/main-header.scss

2022-04-10 21:54 UTC, GanievTimur commented on source/sass/style.scss
> +@use "./source/sass/blocks/common-styles.scss";
Не помогло

2022-04-10 22:02 UTC, DoberBober commented on source/sass/style.scss
> +@use "./source/sass/blocks/common-styles.scss";
fonts и common-styles перенеси на один уровень с styles.scss.
Поправь импорты:
```
@import "./fonts.scss";
@import "./common-styles.scss";
@import "./blocks/main-header.scss";
@import "./blocks/hero-section.scss";
...
```

Ещё не заметил:
contacts-section__email.scss переименовать в contacts-section (по названию блока).
week-product-section__parameters.scss в week-product-section.

2022-04-10 22:03 UTC, DoberBober commented on source/sass/style.scss
> +@use "./source/sass/blocks/common-styles.scss";
Название второго опдключенного шрифта тоже `Open Sans`. У тебя Rubik сейчас стоит.

2022-04-10 22:07 UTC, DoberBober commented on source/sass/style.scss
> +@use "./source/sass/blocks/common-styles.scss";
Файлы, которые на данный момент надо проверить (есть стили, которые лежат не там):
```
reviews-slider-section.scss
main-header.scss
hero-nav.scss
form-section-type.scss
```

2022-04-11 08:02 UTC, GanievTimur commented on source/sass/style.scss
> +@use "./source/sass/blocks/common-styles.scss";
Внес все правки, но стили из scss не переходят в style.css
`[11:00:32] Using gulpfile ~\HTMLacademyLvL2\1946503-mishka-25\gulpfile.js
[11:00:32] Starting 'default'...
[11:00:32] Starting 'styles'...
Error in plugin "sass"
Message:
    source\sass\style.scss
Error: Can't find stylesheet to import.`

2022-04-11 13:41 UTC, DoberBober commented on source/sass/style.scss
> +@use "./source/sass/blocks/common-styles.scss";
Файлы не перенес на один уровень. Вот так должно быть.
![image](https://user-images.githubusercontent.com/18398812/162751971-b82fd9d5-64ac-4172-b6a1-8b7608d4d8a7.png)
Потом удали импорт `@import "./blocks/week-product-section__parameters.scss";` и норм будет. Не забудь правки в подключение шрифта внести (`/../fonts/opensansbold.woff2`).

2022-04-11 14:29 UTC, GanievTimur commented on source/sass/style.scss
> +@use "./source/sass/blocks/common-styles.scss";
Заработало)

2022-04-11 15:53 UTC, merged